// import express from "express";
// import { registerNextRoute } from "../utils/next-route-adapter.js";
// import * as route0 from "../migrated-next/app/api/admin/bundles/route.js";
// import * as route1 from "../migrated-next/app/api/admin/products/route.js";
// import * as route2 from "../migrated-next/app/api/admin/referal/route.js";
// import * as route3 from "../migrated-next/app/api/ai-assistant/route.js";
// import * as route4 from "../migrated-next/app/api/ai-assistant/generate-meeting-summary/route.js";
// import * as route5 from "../migrated-next/app/api/ai-assistant/generate-summary/route.js";
// import * as route6 from "../migrated-next/app/api/ai-assistant/get-summaries/route.js";
// import * as route7 from "../migrated-next/app/api/ai-assistant/get-transcripts/route.js";
// import * as route8 from "../migrated-next/app/api/ai-assistant/meeting-summary/[roomId]/route.js";
// import * as route9 from "../migrated-next/app/api/ai-assistant/meetingIds/route.js";
// import * as route10 from "../migrated-next/app/api/ai-assistant/subtitles/route.js";
// import * as route11 from "../migrated-next/app/api/ai-assistant/tasks/route.js";
// import * as route12 from "../migrated-next/app/api/ai-assistant/tasks/generate/route.js";
// import * as route13 from "../migrated-next/app/api/ai-assistant/transcribe-live/route.js";
// import * as route14 from "../migrated-next/app/api/ai-assistant/voice/route.js";
// import * as route15 from "../migrated-next/app/api/assistant-info/info/route.js";
// import * as route16 from "../migrated-next/app/api/auth/googleLogin/route.js";
// import * as route17 from "../migrated-next/app/api/auth/login/route.js";
// import * as route18 from "../migrated-next/app/api/auth/sendOtp/route.js";
// import * as route19 from "../migrated-next/app/api/auth/signUp/route.js";
// import * as route20 from "../migrated-next/app/api/auth/verifyOtp/route.js";
// import * as route21 from "../migrated-next/app/api/dashboard/route.js";
// import * as route22 from "../migrated-next/app/api/dashboard/files/route.js";
// import * as route23 from "../migrated-next/app/api/dashboard/sessions/route.js";
// import * as route24 from "../migrated-next/app/api/enterprise/users/route.js";
// import * as route25 from "../migrated-next/app/api/events/route.js";
// import * as route26 from "../migrated-next/app/api/holo-assist/profile/route.js";
// import * as route27 from "../migrated-next/app/api/stripe/confirm-order/route.js";
// import * as route28 from "../migrated-next/app/api/stripe/create-checkout/route.js";
// import * as route29 from "../migrated-next/app/api/upload/route.js";
// import * as route30 from "../migrated-next/app/api/user/profile/route.js";
// import * as route31 from "../migrated-next/app/api/user/freeTrial/route.js";
// import * as route32 from "../migrated-next/app/api/user/billing/route.js";
// import * as route33 from "../migrated-next/app/api/user/change-password/route.js";


// const router = express.Router();

// registerNextRoute(router, "/api/admin/bundles", route0, ["get", "post"]);
// registerNextRoute(router, "/api/admin/products", route1, ["get", "post", "put", "delete"]);
// registerNextRoute(router, "/api/admin/referal", route2, ["post", "get", "put", "delete"]);
// registerNextRoute(router, "/api/ai-assistant", route3, ["post"]);
// registerNextRoute(router, "/api/ai-assistant/generate-meeting-summary", route4, ["post"]);
// registerNextRoute(router, "/api/ai-assistant/generate-summary", route5, ["post"]);
// registerNextRoute(router, "/api/ai-assistant/get-summaries", route6, ["get"]);
// registerNextRoute(router, "/api/ai-assistant/get-transcripts", route7, ["post"]);
// registerNextRoute(router, "/api/ai-assistant/meeting-summary/:roomId", route8, ["get"]);
// registerNextRoute(router, "/api/ai-assistant/meetingIds", route9, ["get"]);
// registerNextRoute(router, "/api/ai-assistant/subtitles", route10, ["post"]);
// registerNextRoute(router, "/api/ai-assistant/tasks", route11, ["get", "put"]);
// registerNextRoute(router, "/api/ai-assistant/tasks/generate", route12, ["post"]);
// registerNextRoute(router, "/api/ai-assistant/transcribe-live", route13, ["post", "get"]);
// registerNextRoute(router, "/api/ai-assistant/voice", route14, ["post"]);
// registerNextRoute(router, "/api/assistant-info/info", route15, ["post", "get", "patch"]);
// registerNextRoute(router, "/api/auth/googleLogin", route16, ["post"]);
// registerNextRoute(router, "/api/auth/login", route17, ["post"]);
// registerNextRoute(router, "/api/auth/sendOtp", route18, ["post"]);
// registerNextRoute(router, "/api/auth/signUp", route19, ["post", "get"]);
// registerNextRoute(router, "/api/auth/verifyOtp", route20, ["post"]);
// registerNextRoute(router, "/api/dashboard", route21, ["get"]);
// registerNextRoute(router, "/api/dashboard/files", route22, ["get", "post", "delete"]);
// registerNextRoute(router, "/api/dashboard/sessions", route23, ["get", "post"]);
// registerNextRoute(router, "/api/enterprise/users", route24, ["post", "get"]);
// registerNextRoute(router, "/api/events", route25, ["get", "put"]);
// registerNextRoute(router, "/api/holo-assist/profile", route26, ["get", "post"]);
// registerNextRoute(router, "/api/stripe/confirm-order", route27, ["post", "get"]);
// registerNextRoute(router, "/api/stripe/create-checkout", route28, ["post"]);
// registerNextRoute(router, "/api/upload", route29, ["post"]);
// registerNextRoute(router, "/api/user/profile", route30, ["get"]);
// registerNextRoute(router, "/api/user/profile", route30, ["put"]);
// registerNextRoute(router, "/api/user/freeTrial", route31, ["get","post","put"]);
// registerNextRoute(router, "/api/user/billing", route32, ["get","post"]);
// registerNextRoute(router, "/api/user/change-password", route33, ["get","post","put"]);

// export default router;

import express from "express";
import { registerNextRoute } from "../utils/next-route-adapter.js";
import * as route0 from "../migrated-next/app/api/admin/bundles/route.js";
import * as route1 from "../migrated-next/app/api/admin/products/route.js";
import * as route2 from "../migrated-next/app/api/admin/referal/route.js";
import * as route3 from "../migrated-next/app/api/ai-assistant/route.js";
import * as route4 from "../migrated-next/app/api/ai-assistant/generate-meeting-summary/route.js";
import * as route5 from "../migrated-next/app/api/ai-assistant/generate-summary/route.js";
import * as route6 from "../migrated-next/app/api/ai-assistant/get-summaries/route.js";
import * as route7 from "../migrated-next/app/api/ai-assistant/get-transcripts/route.js";
import * as route8 from "../migrated-next/app/api/ai-assistant/meeting-summary/[roomId]/route.js";
import * as route9 from "../migrated-next/app/api/ai-assistant/meetingIds/route.js";
import * as route10 from "../migrated-next/app/api/ai-assistant/subtitles/route.js";
import * as route11 from "../migrated-next/app/api/ai-assistant/tasks/route.js";
import * as route12 from "../migrated-next/app/api/ai-assistant/tasks/generate/route.js";
import * as route13 from "../migrated-next/app/api/ai-assistant/transcribe-live/route.js";
import * as route14 from "../migrated-next/app/api/ai-assistant/voice/route.js";
import * as route15 from "../migrated-next/app/api/assistant-info/info/route.js";
import * as route16 from "../migrated-next/app/api/auth/googleLogin/route.js";
import * as route17 from "../migrated-next/app/api/auth/login/route.js";
import * as route18 from "../migrated-next/app/api/auth/sendOtp/route.js";
import * as route19 from "../migrated-next/app/api/auth/signUp/route.js";
import * as route20 from "../migrated-next/app/api/auth/verifyOtp/route.js";
import * as route21 from "../migrated-next/app/api/dashboard/route.js";
import * as route22 from "../migrated-next/app/api/dashboard/files/route.js";
import * as route23 from "../migrated-next/app/api/dashboard/sessions/route.js";
import * as route24 from "../migrated-next/app/api/enterprise/users/route.js";
import * as route25 from "../migrated-next/app/api/events/route.js";
import * as route26 from "../migrated-next/app/api/holo-assist/profile/route.js";
import * as route27 from "../migrated-next/app/api/stripe/confirm-order/route.js";
import * as route28 from "../migrated-next/app/api/stripe/create-checkout/route.js";
import * as route29 from "../migrated-next/app/api/upload/route.js";
import * as route30 from "../migrated-next/app/api/user/profile/route.js";
import * as route31 from "../migrated-next/app/api/user/freeTrial/route.js";
import * as route32 from "../migrated-next/app/api/user/billing/route.js";
import * as route33 from "../migrated-next/app/api/user/change-password/route.js";
import * as route34 from "../migrated-next/app/api/enterprise/manager/reps/route.js";
import * as route35 from "../migrated-next/app/api/enterprise/manager/flags/route.js";
import * as route36 from "../migrated-next/app/api/holo-assist/brainFiles/upload/route.js";
import * as route37 from "../migrated-next/app/api/holo-assist/cards/route.js";
import * as route38 from "../migrated-next/app/api/dashboard/skills/route.js";
import * as route39 from "../migrated-next/app/api/dashboard/journal/route.js";

const router = express.Router();

registerNextRoute(router, "/api/admin/bundles", route0, ["get", "post"]);
registerNextRoute(router, "/api/admin/products", route1, ["get", "post", "put", "delete"]);
registerNextRoute(router, "/api/admin/referal", route2, ["post", "get", "put", "delete"]);
registerNextRoute(router, "/api/ai-assistant", route3, ["post"]);
registerNextRoute(router, "/api/ai-assistant/generate-meeting-summary", route4, ["post"]);
registerNextRoute(router, "/api/ai-assistant/generate-summary", route5, ["post"]);
registerNextRoute(router, "/api/ai-assistant/get-summaries", route6, ["get"]);
registerNextRoute(router, "/api/ai-assistant/get-transcripts", route7, ["post"]);
registerNextRoute(router, "/api/ai-assistant/meeting-summary/:roomId", route8, ["get"]);
registerNextRoute(router, "/api/ai-assistant/meetingIds", route9, ["get"]);
registerNextRoute(router, "/api/ai-assistant/subtitles", route10, ["post"]);
registerNextRoute(router, "/api/ai-assistant/tasks", route11, ["get", "put"]);
registerNextRoute(router, "/api/ai-assistant/tasks/generate", route12, ["post"]);
registerNextRoute(router, "/api/ai-assistant/transcribe-live", route13, ["post", "get"]);
registerNextRoute(router, "/api/ai-assistant/voice", route14, ["post"]);
registerNextRoute(router, "/api/assistant-info/info", route15, ["post", "get", "patch"]);
registerNextRoute(router, "/api/auth/googleLogin", route16, ["post"]);
registerNextRoute(router, "/api/auth/login", route17, ["post"]);
registerNextRoute(router, "/api/auth/sendOtp", route18, ["post"]);
registerNextRoute(router, "/api/auth/signUp", route19, ["post", "get"]);
registerNextRoute(router, "/api/auth/verifyOtp", route20, ["post"]);
registerNextRoute(router, "/api/dashboard", route21, ["get"]);
registerNextRoute(router, "/api/dashboard/files", route22, ["get", "post", "delete"]);
registerNextRoute(router, "/api/dashboard/sessions", route23, ["get", "post"]);
registerNextRoute(router, "/api/enterprise/users", route24, ["post", "get"]);
registerNextRoute(router, "/api/events", route25, ["get", "put"]);
registerNextRoute(router, "/api/holo-assist/profile", route26, ["get", "post"]);
registerNextRoute(router, "/api/stripe/confirm-order", route27, ["post", "get"]);
registerNextRoute(router, "/api/stripe/create-checkout", route28, ["post"]);
registerNextRoute(router, "/api/upload", route29, ["post"]);
registerNextRoute(router, "/api/user/profile", route30, ["get"]);
registerNextRoute(router, "/api/user/profile", route30, ["put","get"]);
registerNextRoute(router, "/api/user/freeTrial", route31, ["get","post","put"]);
registerNextRoute(router, "/api/user/billing", route32, ["get","post"]);
registerNextRoute(router, "/api/user/change-password", route33, ["get","post","put"]);
registerNextRoute(router, "/api/enterprise/manager/reps", route34, ["get","post","put"]);
registerNextRoute(router, "/api/enterprise/manager/flags", route35, ["get","post","put"]);
registerNextRoute(router, "/api/holo-assist/brainFiles/upload", route36, ["get","post","put"]);
registerNextRoute(router, "/api/holo-assist/cards", route37, ["get","post","put"]);
registerNextRoute(router, "/api/dashboard/skills", route38, ["get","post"]);
registerNextRoute(router, "/api/dashboard/journal", route39, ["get","post"]);

export default router;
