// app/api/ai-assistant/get-summaries/route.js
import { NextResponse } from "../../../../utils/next-response.js";
import connectDB from "../../../../lib/db.js";
import LegacySummary from "../../../../app/models/Summaries.model.js";
import LiveSummary from "../../../../app/models/MeetingSummary.model.js";

export async function GET(req) {
  try {
    await connectDB();

    const { searchParams } = new URL(req.url);
    const meetingId = searchParams.get("meetingId") || searchParams.get("roomId");
    const userId = searchParams.get("userId");

    if (!meetingId) {
      return NextResponse.json({
        success: false,
        error: "meetingId is required"
      }, { status: 400 });
    }

    const legacyQuery = { meetingId, ...(userId ? { userId } : {}) };
    const liveQuery = { roomId: meetingId, ...(userId ? { userId } : {}) };

    const [legacySummaries, liveSummaries] = await Promise.all([
      LegacySummary.find(legacyQuery).sort({ createdAt: -1 }).lean(),
      LiveSummary.find(liveQuery).sort({ createdAt: -1 }).lean(),
    ]);

    // Merge both sources so sessions generated by either flow show up consistently.
    const merged = [
      ...legacySummaries.map((s) => ({
        id: s._id.toString(),
        summary: s.summary,
        createdAt: s.createdAt,
        type: "general",
      })),
      ...liveSummaries.map((s) => ({
        id: s._id.toString(),
        summary: s.summary,
        createdAt: s.createdAt,
        type: s.type || "general",
      })),
    ].sort((a, b) => new Date(b.createdAt).getTime() - new Date(a.createdAt).getTime());

    const deduped = merged.filter(
      (item, index, arr) => arr.findIndex((other) => other.id === item.id) === index,
    );

    return NextResponse.json({
      success: true,
      data: deduped,
      total: deduped.length,
    }, { status: 200 });

  } catch (error) {
    console.error("❌ Error fetching summaries:", error);
    return NextResponse.json({
      success: false,
      error: error.message || "Failed to fetch summaries"
    }, { status: 500 });
  }
}